name: Deploy Python myflask

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check my code
        uses: actions/checkout@v3

      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest
