name: Deploy Python myflask

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check my code
        uses: actions/checkout@v3

      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r TESTDocker/app/requirements.txt

      - name: Run tests
        run: |
          pytest

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t jimmyomg/my-flask-version2:latest -f TESTDocker/Dockerfile .
          docker push jimmyomg/my-flask-version2:latest
